### ISSUE TITLE
No prefix "backup-on-the-go-" ?

### ISSUE THREAD

**Issue by MoOx** [xuhdev/backup-on-the-go#2]
I am seeing that on your bitbucket home, you don't have the prefix you mentionned in this readme.
I would like to use your tool to mirror my github data on bitbucket and want to avoid the prefix, is there an option for that?

**Comment by xuhdev** [comment]
@MoOx The option is at [line 30 of the template file](https://github.com/xuhdev/backup-on-the-go/blob/heroku/backup.rb#L30).

**Comment by MoOx** [comment]
Thanks for the quick reply. I assume it's disabled by default then.
